# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('blog_name', models.CharField(blank=True, max_length=200, verbose_name='Название блога')),
                ('subscribes', models.ManyToManyField(related_name='subscribers', to='users.Users', verbose_name='Подписчики')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
