# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20171215_1726'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='viewed_records',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='blogs.Record', verbose_name='Просмотренные'),
        ),
        migrations.AlterField(
            model_name='users',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
