# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

def move_users(apps, schema_editor):
    Users = apps.get_model("users", "Users")
    User = apps.get_model("auth", "User")
    for user in Users.objects.all():
        new_user = User(
            id=user.id,
            username=user.username,
            password=user.password,
            first_name=user.first_name,
            last_name=user.last_name,
            last_login=user.last_login,
            date_joined=user.date_joined,
            email=user.email,
            is_active=user.is_active,
            is_staff=user.is_staff,
            is_superuser=user.is_superuser
        )
        new_user.save()
        user.user = new_user
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20171215_1726'),
        ('auth', '0008_alter_user_username_max_length')
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(move_users),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        )
    ]
