# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedrecords',
            name='record',
        ),
        migrations.RemoveField(
            model_name='viewedrecords',
            name='user',
        ),
        migrations.DeleteModel(
            name='ViewedRecords',
        ),
    ]
